### ISSUE TITLE
Redmi AC2100 - 求预装Passwall

### ISSUE THREAD

**Issue by bensk2001** [molun/Auto-Build-OpenWrt#2]
HIHI，你好，非常喜欢你做的OpenWrt固件，非常简单、清爽！
请问可否帮忙在红米AC2100的固件里面默认把Passwall的插件自动编译进去呀？不胜感激~~

**Comment by molun** [comment]
已添加 稍后关注测试下

**Comment by molun** [comment]
> HIHI，你好，非常喜欢你做的OpenWrt固件，非常简单、清爽！
> 请问可否帮忙在红米AC2100的固件里面默认把Passwall的插件自动编译进去呀？不胜感激~~

**Comment by bensk2001** [comment]
感谢感谢，我来刷一下试试~

**Comment by elsakane2015** [comment]
ac2100上没有找到passwall？还是要怎样把它打开？还是大佬又拿掉了？
